Header header

float32 des_fx_r
float32 des_fy_r
float32 des_fz_r
float32 des_tx_r
float32 des_ty_r
float32 des_tz_r

float32 des_fx_l
float32 des_fy_l
float32 des_fz_l
float32 des_tx_l
float32 des_ty_l
float32 des_tz_l

float32 meas_fx_r
float32 meas_fy_r
float32 meas_fz_r
float32 meas_tx_r
float32 meas_ty_r
float32 meas_tz_r

float32 meas_fx_l
float32 meas_fy_l
float32 meas_fz_l
float32 meas_tx_l
float32 meas_ty_l
float32 meas_tz_l
